name: Respuesta del GeoAsesor
on:
  discussion_comment:
    types: [created]

jobs:
  responder:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install azure-ai-inference
        
        - name: Ejecutar Asesor y Guardar Respuesta
        id: asesor_logic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_MODELS_TOKEN }}
        run: |
          # Guardamos la salida del script en una variable de GitHub
          echo "ANSWER<<EOF" >> $GITHUB_ENV
          python scripts/main.py >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publicar comentario en la Discussion
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.discussions.addComment({
              discussion_id: context.payload.discussion.node_id,
              body: process.env.ANSWER
            })
