name: Respuesta del GeoAsesor
on:
  discussion_comment:
    types: [created]

jobs:
  responder:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install azure-ai-inference

      - name: Ejecutar Asesor
        env:
          GITHUB_TOKEN: ${{ secrets.GH_MODELS_TOKEN }}
        run: python scripts/main.py
